# config
cover: /img/colombia.jpg
# logo: /img/logo.png
top_saying:
- title: Jericó, Colombia
#- content: This is a sample content.
# Content
excerpt_link: Read More

#rss: /atom.xml

highlightjs: vs

#Works
#works:
#- works_name: AAA
#  works_url: /
#- works_name: BBB
#  works_url: /atom.xml

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/paulinechin
twitter: https://twitter.com/nomadpauline
linkedin: https://www.linkedin.com/in/paulinechin
instagram: https://www.instagram.com/pauline.chin/
medium: https://medium.com/@pauline.chin


#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
#links:
#- name: Pauline Chin
#  link: http://www.paulinechin.com
#- name: Blog
#  link: blog.paulinechin.com

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
